### ISSUE TITLE
Add support for Polymorphism

### ISSUE THREAD

**Issue by a-musing-moose** [a-musing-moose/morph#10]
We need to add support for polymorphism - That is to say storing multiple types within a single collection. e.g. The classic example of Shape, and then multiple classes which extend it for different types of shape.

Class hierarchy:

Shape
- Circle
- Square
- etc...

**Comment by chrsm** [comment]
I know this is your project, and I'm just commenting on it, but this is for anyone who comes through here and is looking for similar information:

```
/**
 * $collection
 *
 * The name of the collection that this will be stored in
 * 
 * @var string
 */
protected $collection = 'Shape';
```

This is what I am doing for certain types of things that are getting stored; I simply have a property in the document named 'type' which further distinguishes what the object is (for when it's queried out of the DB).

There's also the collection() method..which I just now noticed. -.-
