### ISSUE TITLE
Complex properties don't save if they don't already exist

### ISSUE THREAD

**Issue by mrpoundsign** [a-musing-moose/morph#22]
Hey there. :) Been using morph and it has been working pretty well. I am having an issue when I add a new property to an existing model... I tried to add a "complex" property which is an array of email addresses... seems if the property already existed then an update works, but if the property never existed it doesn't update the record.  e.g.

e.x. {"title":"a title","emails":[]} will update when I set $obj->emails = array('user@example.com') then $obj->save {"title":"a title"} will not.

I haven't yet had the opportunity to try with other property types, so there may be a deeper issue.

**Comment by kkamkou** [comment]
which version? php5.3 or < 5.3?

**Comment by mrpoundsign** [comment]
5.3 -- I am gaving the same problem when I try to make it a Generic property :/ I have been trying to track it down but no luck so far. This is loaded from findOneByQuery then I am trying to update it. Seems the state on all properties is New, if that makes a difference.

**Comment by kkamkou** [comment]
Could u create unittest for this ticket or just put some code here.

**Comment by mrpoundsign** [comment]
Sure I will try to make a unit test for you tomorrow.
On Aug 13, 2011 1:59 PM, "kkamkou" <
reply@reply.github.com>
wrote:

**Comment by kkamkou** [comment]
Brian, any news here? Could u place portion of code here

**Comment by ghost** [comment]
This should solve it:
https://github.com/a-musing-moose/morph/pull/36

**Comment by a-musing-moose** [comment]
@mrpoundsign If as @daniphp say that pull request 36 fixes your issues please do let us know so I can close this issue?
