### ISSUE TITLE
Get single Document

### ISSUE THREAD

**Issue by russellseymour** [a-musing-moose/morph#25]
Hello again,

I feel that I might be missing something very obvious here again, so please accept my apologies in advance.

Sometimes I run a query that I know will return either 0 or 1 records.  Testing for the count is easy, however I am having problems with the iterator object when I want to get the 1 document that is returned.

I have tried to use the next() and current() methods, but I do not get a valid object back.  Indeed i get the following error when I used current():

`PHP Catchable fatal error:  Argument 1 passed to morph\Iterator::createObject() must be an array, null given, called in phar:///turtle/ngsites/shared/phplib/Morph.phar/Iterator.php on line 104 and defined in phar:///turtle/ngsites/shared/phplib/Morph.phar/Iterator.php on line 86`

The only way that I have been able to get the single document into an object is to run the foreach command, e.g.:

`foreach ($result as $stored) {}`

But that does not feel right.

Thanks again,

Russell

**Comment by a-musing-moose** [comment]
The results from a findByQuery are an Iterator - You have to iterator (foreach) over it to get the objects.  If you are only trying to get a single item use the findOneByQuery() of create an instance of the object and use the loadById() functions.  The findOneByQuery will return a single object. The loadById will load the specified id into the current object.

Hope that makes sense.

**Comment by russellseymour** [comment]
Again thanks very much, I had forgotten about the fineByOneQuery method.

Russell
