### ISSUE TITLE
how do I delete a record ?

### ISSUE THREAD

**Issue by zivhsiao** [a-musing-moose/morph#40]
I tried to delete some record but failed.

my code below:

$query = new \morph\Query();
$query->property('title')->equals('test');

$rs = $scraped->findByQuery($query);
$scraped->deleteByQuery($query);

something wrong ? please tell me the right way, thanks!

**Comment by kkamkou** [comment]
```
echo 'total: ' . $rs->totalCount();
foreach ($rs as $record) {
    $record->delete();
}
```
