### ISSUE TITLE
Saving Array question

### ISSUE THREAD

**Issue by Gorbov** [a-musing-moose/morph#43]
How can I save an array of user's email?

$emails = array('aa@aa.com','bb@bb.com', ...)

or, for example,
currency array
$currs = array('USD','EUR', ...)

I mean, witch Property Type?
...
->addProperty(new \morph\property\ {...} ('emails'))
...

Is it possible?

**Comment by Bobby1984** [comment]
Hi,

I have made something alike with an ->addProperty(new \morph\property\Generic("names"), array())

**Comment by a-musing-moose** [comment]
Hi,

Have you looked at the StatefulCollection property. It acts like an array.

The problem with just using the generic property with an array is that addtions/removals etc from the array do not trigger a state change in the model, and therefore it won't know that it is dirty and needs saving.
