### ISSUE TITLE
Add composer.json and add module to packagist

### ISSUE THREAD

**Issue by seyfer** [a-musing-moose/morph#48]
Please. 
Or this lib useless.

**Comment by a-musing-moose** [comment]
Hi @seyfer, I haven't worked with PHP for some time and have not experience of composer. I am of course happy to consider pull requests to add the required feature.

**Comment by seyfer** [comment]
It's required your credentials as author and also your account at packagist.
If I add it by myself it will be bounded to my account.. so I can't, because it's your module.
